apiVersion: v1
kind: Service
metadata:
  name: {{ include "hf-orderer.fullname" . }}
  labels:
{{ include "hf-orderer.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 7050
      protocol: TCP
      name: orderer-port
  selector:
    app.kubernetes.io/name: {{ include "hf-orderer.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
