{{- if .Values.storage.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hf-ca.fullname" . }}-mysql
  labels:
{{ include "hf-ca.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.storage.mysql.port }}
      targetPort: 3306
      protocol: TCP
      name: mysql-port
  selector:
    app.kubernetes.io/name: {{ include "hf-ca.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}