{{- if .Values.storage.pg.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hf-ca.fullname" . }}-pg
  labels:
{{ include "hf-ca.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.storage.pg.port }}
      targetPort: 5432
      protocol: TCP
      name: mysql-port
  selector:
    app.kubernetes.io/name: {{ include "hf-ca.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}