apiVersion: v1
kind: Service
metadata:
  name: {{ include "hf-ca.fullname" . }}
  labels:
{{ include "hf-ca.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 7054
      protocol: TCP
      name: ca-port
  selector:
    app.kubernetes.io/name: {{ include "hf-ca.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
