apiVersion: v1
kind: Service
metadata:
  name: {{ include "hf-peer.fullname" . }}
  labels:
{{ include "hf-peer.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.portRequest }}
      targetPort: 7051
      protocol: TCP
      name: request
    - port: {{ .Values.service.portEvent }}
      targetPort: 7053 
      protocol: TCP 
      name: event
  selector:
    app.kubernetes.io/name: {{ include "hf-peer.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
